local bbr=function()return(function()
svarsEnv.supportedMissions_Env['general9'] = true
svarsEnv.supportedMissions_Env['default2'] = true
svarsEnv.supportedMissions_Env['default3'] = true
svarsEnv.supportedMissions_Env['general12'] = true
svarsEnv.supportedMissions_Env['general13'] = true
svarsEnv.supportedMissions_Env['general15'] = true
svarsEnv.supportedMissions_Env['general16'] = true
svarsEnv.supportedMissions_Env['general30'] = true
svarsEnv.supportedMissions_Env['general31'] = true
svarsEnv.supportedMissions_Env['general33'] = true
svarsEnv.supportedMissions_Env['general35'] = true
svarsEnv.supportedMissions_Env['general36'] = true
svarsEnv.supportedMissions_Env['general39'] = true
svarsEnv.supportedMissions_Env['general40'] = true
svarsEnv.supportedMissions_Env['general45'] = true
svarsEnv.supportedMissions_Env['general47'] = true
svarsEnv.supportedMissions_Env['general49'] = true
svarsEnv.supportedMissions_Env['general51'] = true
svarsEnv.supportedMissions_Env['general55'] = true
end)()end;bbr()
